### findAll Personas
GET http://localhost:3000/api/persona

### getOne Persona (Ejemplo buscando al Veterinario por DNI)
GET http://localhost:3000/api/persona/33333333

### ----------------------------------------------------
### CREACIÓN DE ROLES
### ----------------------------------------------------

### create Persona Normal (Ej: Posible Donante)
POST http://localhost:3000/api/persona
Content-Type: application/json

{
    "dni": "55555555",
    "nombre": "Manuel",
    "apellido": "Ferraris",
    "email": "FMprueba5@email.com",
    "contrasenia": "ab123456",
    "telefono": "3415550001"
}

### create Persona Colaborador
POST http://localhost:3000/api/persona
Content-Type: application/json

{
    "dni": "22222222",
    "nombre": "Lucía",
    "apellido": "Fernández",
    "email": "lucia.colab@sara.org",
    "contrasenia": "password123",
    "telefono": "3415550002",
    "id_colaborador": "COL-001"
}

### create Persona Veterinario
POST http://localhost:3000/api/persona
Content-Type: application/json

{
    "dni": "33333333",
    "nombre": "Martín",
    "apellido": "López",
    "email": "martin.vet@clinicavet.com",
    "contrasenia": "password123",
    "telefono": "3415550003",
    "matricula": "MP-9876",
    "anios_experiencia": 8
}

### create Persona Adoptante
POST http://localhost:3000/api/persona
Content-Type: application/json

{
    "dni": "12121212",
    "nombre": "Natalia",
    "apellido": "Romero",
    "email": "natalia@email.com",
    "contrasenia": "ab123456",
    "telefono": "3415550004",
    "id_adoptante": "ADO-102",
    "estado": "Apto",
    "domicilio": "Av. Pellegrini 1234, Rosario"
}

### ----------------------------------------------------
### ACTUALIZACIÓN Y BORRADO
### ----------------------------------------------------

### update Persona (Ejemplo: El donante normal decide volverse Adoptante)
PUT http://localhost:3000/api/persona/11111111
Content-Type: application/json

{
    "id_adoptante": "ADO-103",
    "estado": "En evaluación",
    "domicilio": "Bv. Oroño 456, Rosario"
}

### delete Persona
DELETE http://localhost:3000/api/persona/11111111