### findAll Donaciones
GET http://localhost:3000/api/donacion

### getOne Donacion (Ejemplo con nro_donacion = 1)
GET http://localhost:3000/api/donacion/1

### ----------------------------------------------------
### CREACIÓN DE DONACIONES (Usando el DNI de Roberto)
### ----------------------------------------------------

### create Donacion - Insumos (con fecha de vencimiento)
POST http://localhost:3000/api/donacion
Content-Type: application/json

{
    "tipo": "Alimento",
    "cantidad": 10,
    "descripcion": "Bolsas de alimento balanceado para perro adulto (15kg c/u)",
    "fecha_vencimiento": "2027-05-10",
    "dni_donante": "11111111"
}

### create Donacion - Monetaria (sin fecha de vencimiento)
POST http://localhost:3000/api/donacion
Content-Type: application/json

{
    "tipo": "Monetaria",
    "cantidad": 50000,
    "descripcion": "Transferencia bancaria para cubrir gastos de cirugías",
    "dni_donante": "11111111"
}

### ----------------------------------------------------
### ACTUALIZACIÓN Y BORRADO
### ----------------------------------------------------

### update Donacion (Ejemplo: actualizar la cantidad ingresada)
PUT http://localhost:3000/api/donacion/1
Content-Type: application/json

{
    "cantidad": 12,
    "descripcion": "Bolsas de alimento balanceado para perro adulto (15kg c/u) - Corregido por error de conteo"
}

### delete Donacion
DELETE http://localhost:3000/api/donacion/2