### findAll Animales
GET http://localhost:3000/api/animal

### getOne Animal (Ejemplo con nro_animal = 1)
GET http://localhost:3000/api/animal/1

### create Animal
POST http://localhost:3000/api/animal
Content-Type: application/json

{
    "especie": "Perro",
    "raza": "Labrador",
    "edad_estimada": 5,
    "fecha_ingreso": "2026-06-15",
    "estado": "Disponible",
    "sexo": "Macho",
    "peso": 30.5,
    "descripcion": "Un perro amigable y juguetón."
}

### update Animal (Ejemplo: actualizar estado y peso)
PUT http://localhost:3000/api/animal/1
Content-Type: application/json

{
    "estado": "Adoptado",
    "peso": 31.2
}

### delete Animal
DELETE http://localhost:3000/api/animal/4