### findAll Vacunas
GET http://localhost:3000/api/vacuna

### getOne Vacuna (Ejemplo con nro_vacuna = 1)
GET http://localhost:3000/api/vacuna/1

### ----------------------------------------------------
### CREACIÓN DE VACUNAS
### ----------------------------------------------------

### create Vacuna - Antirrábica
POST http://localhost:3000/api/vacuna
Content-Type: application/json

{
    "droga": "Antirrábica Canina",
    "stock": 50,
    "fecha_ingreso": "2026-07-20",
    "fecha_vencimiento": "2027-07-20"
}

### create Vacuna - Sextuple
POST http://localhost:3000/api/vacuna
Content-Type: application/json

{
    "droga": "Séxtuple",
    "stock": 25,
    "fecha_ingreso": "2026-07-15",
    "fecha_vencimiento": "2027-12-01"
}

### ----------------------------------------------------
### ACTUALIZACIÓN Y BORRADO
### ----------------------------------------------------

### update Vacuna (Ejemplo: descontar stock por colocaciones del día)
PUT http://localhost:3000/api/vacuna/1
Content-Type: application/json

{
    "stock": 38
}

### delete Vacuna (Ejemplo: lote vencido que se descarta)
DELETE http://localhost:3000/api/vacuna/2