### 1. CREAR UN RESCATE
POST http://localhost:3000/api/rescate
Content-Type: application/json

{
    "numero_persona": 2,
    "numero_animal": 3,
    "fecha_hora": "2026-05-24T20:30:00.000Z",
    "lugar_rescate": "Av. Pellegrini y Bv. Oroño, Rosario"
}

### Actualizar rescate
PUT http://localhost:3000/api/rescate/2/3/2026-05-24T20:30:00.000Z
Content-Type: application/json

{
    "lugar_rescate": "Av. Pellegrini y Bv. Oroño, Rosario - Actualizado"
}

### 2. OBTENER TODOS LOS RESCATES
# Esto debería devolverte el rescate que acabas de crear arriba.
GET http://localhost:3000/api/rescate


### 3. OBTENER UN SOLO RESCATE POR SU CLAVE PRIMARIA COMPUESTA
# La URL debe coincidir exactamente con los 3 datos que usaste en el POST.
# Fíjate cómo la fecha viaja directamente en la URL como string.
GET http://localhost:3000/api/rescate/1/9/2026-05-24T20:30:00.000Z