### findAll Rescates
GET http://localhost:3000/api/rescate

### getOne Rescate (Ejemplo con nro_rescate = 1)
GET http://localhost:3000/api/rescate/1

### ----------------------------------------------------
### CREACIÓN DE RESCATES
### ----------------------------------------------------

### create Rescate 
POST http://localhost:3000/api/rescate
Content-Type: application/json

{
    "dni_persona": "22222222",
    "nro_animal": 1,
    "fecha_rescate": "2026-08-20",
    "lugar_rescate": "Av. Pellegrini e Italia, cerca del parque"
}

### ----------------------------------------------------
### ACTUALIZACIÓN Y BORRADO
### ----------------------------------------------------

### update Rescate (Ejemplo: Se corrige la dirección del rescate)
PUT http://localhost:3000/api/rescate/1
Content-Type: application/json

{
    "lugar_rescate": "Av. Pellegrini y Dorrego (esquina de la plaza)"
}

### delete Rescate (Ejemplo: Se cargó un rescate por error) (no esta codeado el DELETE!!!)
DELETE http://localhost:3000/api/rescate/2