### findAll Entrevistas
GET http://localhost:3000/api/entrevista

### getOne Entrevista (Ejemplo con id_entrevista = 1)
GET http://localhost:3000/api/entrevista/1

### ----------------------------------------------------
### CREACIÓN DE ENTREVISTAS
### ----------------------------------------------------

### create Entrevista - Inicial
POST http://localhost:3000/api/entrevista
Content-Type: application/json

{
    "dni_adoptante": "44444444",
    "dni_colaborador": "22222222",
    "fecha_hora": "2026-08-15T10:00:00Z",
    "estado": "Programada",
    "aprobada": false
}

### ----------------------------------------------------
### ACTUALIZACIÓN Y BORRADO
### ----------------------------------------------------

### update Entrevista - Reprogramación (Adoptante no pudo asistir)
PUT http://localhost:3000/api/entrevista/1
Content-Type: application/json

{
    "fecha_hora_rep": "2026-08-20T16:30:00Z",
    "estado": "Reprogramada",
    "descripcion": "El adoptante avisó con antelación por temas laborales."
}

### update Entrevista - Resolución Final (Aprobada)
PUT http://localhost:3000/api/entrevista/1
Content-Type: application/json

{
    "estado": "Finalizada",
    "descripcion": "La familia cumple con todos los requisitos. Tienen patio cerrado y buena predisposición.",
    "aprobada": true
}

### delete Entrevista (Ejemplo: Error de carga)
DELETE http://localhost:3000/api/entrevista/2